name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'sbt'

      - name: Extract version from tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "PROJECT_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "PROJECT_VERSION=dev-build" >> $GITHUB_ENV
          fi

      - name: Build JAR
        run: |
          sbt/sbt 'set version := "'"$PROJECT_VERSION"'"' assembly
          mv target/scala-2.11/*-assembly-*.jar royalroad-downloader.jar

      - name: Release
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: royalroad-downloader.jar
          fail_on_unmatched_files: true
